### ISSUE TITLE
Occurred 'cp949' error in IniConfig class

### ISSUE THREAD

**Issue by melemo2** [pytest-dev/iniconfig#36]
@RonnyPfannschmidt 
![image](https://user-images.githubusercontent.com/67433064/145445384-4cd4ea02-3e09-447e-b0ba-9e9f0d7b0d45.png)

I solved that issue #37
```python
f = open(self.path) -> f = open(self.path, encoding='utf-8')
```

**Comment by RonnyPfannschmidt** [comment]
@melemo2 please elaborate on the python version involved 

im happy to add a sane or configriuable default, but im slightly hesitant to just put that in as is
(we have had issues with people using their native language encoding instead of utf8 before)

**Comment by melemo2** [comment]
@RonnyPfannschmidt 
python version is 3.9.7
Detailed error msg and call stack is here
https://github.com/scikit-learn/scikit-learn/issues/21933
I don't know why error occurred..
should I close this issue?

**Comment by RonnyPfannschmidt** [comment]
i believe this needs addressing, based on the links i'm also under the impression this happened to youu by accident as your editor use utf8 and your system encoding isnt

i should ensure we open files more safely later on

**Comment by melemo2** [comment]
@RonnyPfannschmidt
thanks for your comment
I think you're right :)
It would be better to support both none and utf-8.
by handling an 'UnicodeDecodeError' Exception

**Comment by Fengjun-Wang** [comment]
Hi @RonnyPfannschmidt and @melemo2  , 

If we can provide options on the encoding format, it could resolve problems for developer who are using Windows as development os. 
For example, as melemo2 mentioned, the scikit-learn has a "setup.cfg" file which is encoded as "utf8", however, some Windows os has default encoding ```cp936```. 

My idea is we can provide an additional param whose default value is ```utf-8```. 
What do you think?

@melemo2 are you still working on MRG #37 ?

**Comment by melemo2** [comment]
@Fengjun-Wang

nope. I'll close it
I mentioned problem already had been solved by just reinstall a project, so I'm not interested this issue.

but I think it's easier to handle exceptions than using parameter
cuz If we add a parameter then another huge projects need to be modified :)
