### ISSUE TITLE
Specify encoding explictly in the `IniConfig` constructor

### ISSUE THREAD

**Issue by inwaves** [pytest-dev/iniconfig#48]
Hi!

Since Python 3.10 there's a new `EncodeWarning` that gets flagged when a file is opened without specifying an encoding. PR [#10328](https://github.com/pytest-dev/pytest/pull/10328) in pytest proposes adding this capability. For this to work, a bunch of calls need to be updated to explicitly specify `encoding="utf-8"` (or something similar – though UTF-8 seems like a sensible default).

Some of the tests, like [`test_ini_markers_whitespace`](https://github.com/pytest-dev/pytest/blob/9fbd67dd4b1baa6889dbb2073c17b85da39f80d9/testing/test_mark.py#L104), initialise an `IniConfig` object, whose constructor opens a file without specifying an encoding (see [here](https://github.com/pytest-dev/iniconfig/blob/1022b07e34bdb1fd378eaedee0bef8c98d77aaf4/src/iniconfig/__init__.py#L51)). This leads to the test failing.

Can we modify the constructor to use an explicit encoding when opening the file? If `iniconfig` doesn't support UTF-8 we can just use ASCII – so long as something is specified.

Thanks!

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus its actually on my todo for today ^^

**Comment by nicoddemus** [comment]
Ahh sorry for assuming hehehe. :+1:
