### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by mgorny** [pytest-dev/iniconfig#50]
The tests in the current release no longer works with recent versions of `pytest` due to `py.test` removal. Could you please make a new release with the changes from main?

**Comment by RonnyPfannschmidt** [comment]
There is some work to be done to complete the release, I'll get back to it between the days

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/iniconfig/releases/tag/v2.0.0 is out
